### PR TITLE
Fixed default options when init

### PR DESCRIPTION
**Pull request by Tiscs**
I'm so sorry about my PR #342.
I fixed by set default value for options.

### CODE REVIEW

**Comment by nebiros** [comment]
not merged yet?, 😅

**Comment by petervanderdoes** [comment]
It's fixed, just nor using the PR.

**Comment by nebiros** [comment]
@petervanderdoes I'm using the homebrew version:

```
14:42 $ git flow version
1.12.2 (AVH Edition)
```

Still doesn't work:

```
How to name your supporting branch prefixes?
Feature branches? [] feature/
Bugfix branches? [] bugfix/
Release branches? [] release/
Hotfix branches? [] hotfix/
Support branches? [] support/
Version tag prefix? []
```

**Comment by petervanderdoes** [comment]
Using brew myself:
```shell
petervanderdoes:~/a/mozjpeg$ git flow init -d
Initialized empty Git repository in /Users/petervanderdoes/a/mozjpeg/.git/
Using default branch names.
No branches exist yet. Base branches must be created now.
Branch name for production releases: [master]
Branch name for "next release" development: [develop]

How to name your supporting branch prefixes?
Feature branches? [feature/]
Bugfix branches? [bugfix/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
Hooks and filters directory? [/Users/petervanderdoes/a/mozjpeg/.git/hooks]
```

**Comment by yansheng836** [comment]
> @petervanderdoes I'm using the homebrew version:
> 
> ```
> 14:42 $ git flow version
> 1.12.2 (AVH Edition)
> ```
> 
> Still doesn't work:
> 
> ```
> How to name your supporting branch prefixes?
> Feature branches? [] feature/
> Bugfix branches? [] bugfix/
> Release branches? [] release/
> Hotfix branches? [] hotfix/
> Support branches? [] support/
> Version tag prefix? []
> ```

Maybe this will help you https://github.com/petervanderdoes/gitflow-avh/issues/393#issuecomment-460925585.

**Pull request closed without merging**
