### PR TITLE
Issue #243 Add AVH meaning.

### PR DESCRIPTION
**Pull request by ecararus**
Documentation never mentions what "AVH" stands for #243

### CODE REVIEW

**Comment by petervanderdoes** [comment]
Closed per commit: 1d73af4b14b2cee524f19a3bc50477bdd3a82119

**Comment by a-x-** [comment]
what is `A VirtualHome`?

**Comment by a-x-** [comment]
What the differences of usual git-flow?

**Comment by a-x-** [comment]
ok, I found: https://github.com/petervanderdoes/gitflow-avh/wiki/FAQ

Add this description to the begin on readme please

**Pull request closed without merging**
