### PR TITLE
GitHub support

### PR DESCRIPTION
**Pull request by lgiordani**
This implements the idea expressed here http://lgiordani.com/blog/2015/06/22/using-gitflow-with-github-a-simple-procedure/.

I don't know if you want to include GitHub support in gitflow. I developed it because I use both the workflows and having a set of command embedded in gitflow is very good for me.

---
This change is [Reviewable](https://reviewable.io/reviews/petervanderdoes/gitflow-avh/208)

### CODE REVIEW

**Comment by moroine** [comment]
:+1:

**Comment by kaluzki** [comment]
+1

**Comment by wadkar** [comment]
@petervanderdoes I was wondering what your thoughts are on this?
I am currently avoiding use of `git flow feature finish` and manually merging published `feature/*` to my `develop`.

This could be a nice addition to `git-flow-avh` unless you have some other suggestion?

**Comment by mknippen** [comment]
This would be amazing!

**Comment by kkarimi** [comment]
+1

**Comment by lgiordani** [comment]
This has been sitting here since 2015, I think it's clearly not interesting for the team. I'm going to close it

**Pull request closed without merging**
